/* AUTOGENERATED */
Ϣ  =  window ; 

Ϣ . notab  =   (x,...𝔸)=> ((x . tabIndex  =   - 1) , x)
Ϣ . domswap  =   (x,y,...𝔸)=> y . parentNode . insertBefore(y , x) ; 

Ϣ . textButton  =  (x , ƒ , 𝕂) => {  const  ə  =  mkə(`button` , { ... (𝕂 || {})} , `${x}`)
                        ə . onclick  =  ƒ ; 
                         return ə ;  } ; 
Ϣ . toggleButton  =  (ƒ , N , Y , S =  false  , set_init =  true ) => {
  S  =   +  !  ! S ; 
   if (isStr(N)) [N , Y]  =  [N , Y] . ᴍ( (x,...𝔸)=>  mkə(`button` , {[`𝑆`] : `height: 100%; 𝚙𝚕: 6px; 𝚙𝚛: 6px; border: none;`} , `${x}`)) ; 
   let  n  =  mkə( false  , {} ,  false ) ; 
   let  ə  =  S ? Y : N ; 
  n . replaceWith(ə) ; 
   const  ꬶ  =  ə . onclick  =   (...𝔸)=> { n . replaceWith(ə) ; 
                       ə . replaceWith(n  =  (S =  ! S) ? Y : N) ; 
                       n . onclick  =  ꬶ ; 
                        return ƒ(S) ;  }
   if (set_init) ƒ(S) ; 
   return ə ;  } ; 
Ϣ . textField  =  (Ѧ) => { 
   let  ə ; 
   let  fld  =  mkə(`input` , {[`𝑆`] : `min-width: 0; padding: 2px; flex-grow: 1; height: 100%; border: none;` ,  ... (Ѧ)} ,  false ) ; 
   if (Ѧ . þ0F070 || Ѧ . þ0F06E) { ə  =  mkə(`span` , {[`𝐶`] : `boxInput` , [`𝑆`] : `width: 100%;`} , [(fld) , (notab(toggleButton( (x,...𝔸)=> (fld . type  =  ["password" , "text"][ + x]) , "" , "")))]) ;  }
   else { ə  =  mkə(`span` , {[`𝐶`] : `boxInput` , [`𝑆`] : `width: 100%;`} , fld) ;  }
  ə . 𝚒  =  fld ; 
   return ə ;  }
Ϣ . box  =  (Ѧ ,  ... C) => { 
   return  mkə(`div` , {[`𝐶`] : `box` , [`𝑆`] : `display: flex; flex-direction: column; align-items: center;`} , C)
} ; 



Ϣ . popup  =  (Ѧ , c) => {
   let  ə , btn ; 
  (ə = mkə(`dialog` , {[`closedby`] : Ѧ . þ0F2D4 ? `any` : `none`} , [(Ѧ . þF0159  ? ((btn = mkə(`button` , {[`𝐶`] : `dialogCloseBtn`} , `✗`))) :  []) , (c)]))
  ə . addEventListener(`close` ,   (...𝔸)=> (Ѧ . onclose ?. () , ə . remove())) ; 
  (btn ?? {}) . onclick  =   (...𝔸)=> ə . close() ; 
   if ( ! Ѧ . noAppend) { þF0219 . body . append(ə) ; 
                   ə . showModal() ;  }
   return ə } ; 

Ϣ . table  =  (Ѧ , rows) => {
   let  ə ; 
  (ə = mkə( false  , {[`𝐶`] : `table` , [`𝑆`] : `grid-template-columns: repeat(${ þ1F0CC (rows[0])},minmax(max-content, 1fr));` ,  ... (Ѧ)} , rows . flat() . ᴍ( (x,...𝔸)=> mkə(`div` , {[`𝐶`] : `tableItem`} , x))))
   return ə ;  } ; 

Ϣ . pageNumBar  =  (Ѧ , N , n = 0) => {
   let  ə , 𝙱 , 𝚕 , 𝚛 ; 
  Ѧ . N      ??=  N ; 
  Ѧ . w      ??=  1 ;  
  Ѧ . d_off  ??=  1 ; 
  Ѧ . n      ??=  n ; 
  (ə = mkə(`span` , {[`𝐶`] : `pageNumBar`} , [
    (𝚕 = mkə(`button` , {[`𝐶`] : `pageNumPrev`} , `←`)) , 
     ... 𝙱 =  þ02B65 ( (Math.min) (2 * Ѧ . w + 1 , Ѧ . N)) . ᴍ( (x,...𝔸)=> mkə(`button` , {[`𝐶`] : `pageNumButton`} ,  false )) , 
    (𝚛 = mkə(`button` , {[`𝐶`] : `pageNumNext`} , `→`)) ]))
   þ021A8 (𝙱) . ꟿ( (x,y,...𝔸)=> y . onclick =  (...𝔸)=> Ѧ . setN( undefined  , x)) ; 
  𝚕 . onclick  =   (...𝔸)=> Ѧ . setN(Ѧ . n - 1) ; 
  𝚛 . onclick  =   (...𝔸)=> Ѧ . setN(Ѧ . n + 1) ; 
   const  G  =  (n) => {  const  [L , R]  =  [0 , Ѧ . N - 1] ; 
             n  =   þF7E44 (n , 0 , R) ; 
              if (Ѧ . N <= 1 + 2 * Ѧ . w)  return [L , n , R] ; 
              let  [l , r]  =  [ (Math.max) (n - Ѧ . w , L) ,  (Math.min) (n + Ѧ . w , R)] ; 
              if (l < L + Ѧ . w)  return [l ,  n ,   (Math.min) (l + 2 * Ѧ . w , R)] ; 
              if (r > R - Ѧ . w)  return [ (Math.max) (r - 2 * Ѧ . w , L) ,  n ,  r] ; 
              return [l , n , r] ;  } ; 
  Ѧ . setN  =  (n = Ѧ . n , i =  undefined  , activate =  true ) => {
     let  l , r ;  [l , Ѧ . n , r]  =  G(i ===  undefined   ? n :  G(Ѧ . n)[0] + i) ; 
    [𝚕 . disabled , 𝚛 . disabled]  =  [Ѧ . n == 0 ,  Ѧ . n == Ѧ . N - 1] ; 
     for ( const [i , σ] of  þ021A8 ( þF7E3B (l , r))) {
      [𝙱[i] . n , 𝙱[i] . innerText]  =  [σ , σ + Ѧ . d_off] ; 
       if (σ == Ѧ . n) { 𝙱[i] . classList  . add(`selectedPageNum`) ;  𝙱[i] . disabled  =   true  ;  }
       else        { 𝙱[i] . classList  . remove(`selectedPageNum`) ;  𝙱[i] . disabled  =   false  ;  } }
     if (activate) Ѧ . updatePage ?. (Ѧ . n) ; 
     print (Ѧ) ;  }
  Ѧ . setN() ; 
  ə . Ѧ  =  Ѧ ; 
   return ə ;  } ; 

 const  AEL  =   (x,...𝔸)=> x . addEventListener( ... 𝔸) ; 
 const  RAT  =   (x,...𝔸)=> x . removeAttribute ( ... 𝔸) ; 

 let  [𝘥 , 𝘵]  =  [null , null] ; 
 const  αoverβ  =  (α , β , s) => {
   if (α === β  ||   ! (α && β))  return  ; 
   const  [v , A]  =  [α . attributes . dragItem . value , β . attributes] ; 
   if ( ! (v == A . dragItem ?. value  ||  v == A . dragHold ?. value))  return  ; 
   if (s) { SAT(β , `maydrop` ,  "" ) ; 
          if (𝘵  &&  𝘵 !== β) RAT(𝘵 , `maydrop` ,  "" ) ; 
         𝘵  =  β ;  }
   else  RAT(β , `maydrop` ,  "" ) ;  } ; 
 const  confDrag  =  (þ0E27F , 𝚒) => {
  AEL(þ0E27F , `dragenter` , (𝜺) => αoverβ(𝘥 , 𝜺 . target ,  true )) ; 
  AEL(þ0E27F , `dragleave` , (𝜺) => αoverβ(𝘥 , 𝜺 . target ,  false )) ; 
  AEL(þ0E27F , `dragover`  , (𝜺) => 𝜺 . preventDefault()) ; 
   return þ0E27F ;  } ; 
Ϣ . dragItem  =  (þ0E27F , 𝚒 = 0) => {
  𝚒  =   ""  + 𝚒 ; 
  SAT(þ0E27F , `dragItem`  , 𝚒     ) ; 
  SAT(þ0E27F , `draggable` , `true`) ; 
  AEL(þ0E27F , `dragstart` ,  (...𝔸)=> { SAT(þ0E27F , `dragging` ,  "" ) ;  𝘥 = þ0E27F ;  }) ; 
  AEL(þ0E27F , `dragend`   ,  (...𝔸)=> { RAT(þ0E27F , `dragging`  ) ; 
                       αoverβ(𝘥 , 𝘵 ,  false ) ;  𝘥 = null ;  }) ; 
  AEL(þ0E27F , `drop`      ,  (...𝔸)=> þ0E27F === 𝘵  &&  swapə(𝘥 , 𝘵)) ; 
   return confDrag(þ0E27F , 𝚒) ;  } ; 
Ϣ . dragHold  =  (þ0E27F , 𝚒 = 0) => {
  𝚒  =   ""  + 𝚒 ; 
  SAT(þ0E27F , `dragHold` ,  𝚒    ) ; 
  AEL(þ0E27F , `drop`     ,  (...𝔸)=> þ0E27F === 𝘵  &&  þ0E27F . append(𝘥)) ; 
   return confDrag(þ0E27F , 𝚒) ;  } ; 