/* AUTOGENERATED */
BASE_CHARSET  =  'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789' ; 

þF0219  =  document ; 
[𝐴 , 𝐸 , 𝑜]  =  [Array , Element , Object] ; 
[𝒪 , 𝒟 , 𝒪k , 𝒪v]  =  [𝑜 . entries , 𝑜 . fromEntries , 𝑜 . keys , 𝑜 . values] ; 
𝔓  =   (x,...𝔸)=> x . prototype ; 
𝔍  =  {þ02191 : JSON . stringify ,  þ02193 : JSON . parse} ; 
 þF7E5D   =  String . fromCharCode ; 
 þ1F0CC   =   (x,...𝔸)=> x . length ; 
𝗙  =   (x,...𝔸)=> x instanceof Function ; 
𝑙  =   (x,...𝔸)=> [ ... x] ; 
 þF0EFE   =   (x,...𝔸)=> x ; 
[ þF114F  ,  þ02B13 ]  =  [Math . random ,  Math . floor] ; 
[ (Math.max)  ,  (Math.min) ]  =  [Math . max , Math . min] ; 
 þF7E44       =   (x,y,z,...𝔸)=>  (Math.min) ( (Math.max) (x , y) , z)
 þ021A8   =   (x,...𝔸)=> [ ... x] . map((x , i) => [i , x])
 þ02B65   =   (x,y,...𝔸)=> isArray(x)  ? [ ... x . keys()] :   þ02B65 (𝐴(y ===  undefined  ? x : y - x)) . ᴍ((v) => v + (y ===  undefined  ? 0 : x)) ; 
 þF7E3B   =   (x,y,...𝔸)=> isArray(x)  ?  þ02B65 (a . length + 1) :  y ===  undefined   ?  þ02B65 (x + 1) :   þ02B65 (x , y + 1) ; 
 þF147C   =  ( ... 𝙰) =>  þ02B65 ( (Math.max) ( ... 𝙰 . ᴍ( þ1F0CC ))) . ᴍ((i) => 𝙰 . ᴍ( (x,...𝔸)=> x[i])) ; 
ᴍv  =   (x,y,...𝔸)=> 𝒟(𝒪(x) . ᴍ(([k , v]) => [k , y(v)])) ; 
ᴍk  =   (x,y,...𝔸)=> 𝒟(𝒪(x) . ᴍ(([k , v]) => [y(k) , v])) ; 
𝒮  =  (d , k , v) => ( ! (k in d)  ||  d[k] === null)  ? (d[k] = v) :  d[k] ; 
 print       =  ( ... x) => (console . log  ( ... x) , x[0]) ; 
table  =  ( ... x) => (console . table( ... x) , x[0]) ; 
ends   =  (l) => l . map((𝑥 , i) => [i == 0 , 𝑥 , i ==  þ1F0CC (l) - 1]) ; 
merge  =   (...𝔸)=> 𝑜 . assign({} ,  ... 𝔸) ; 
sleep  =  (s) =>  new Promise((r) => setTimeout(r , 1000 * s)) ; 
mk_id  =  (l , chars = BASE_CHARSET) =>  þ02B65     (l) . ᴍ( (...𝔸)=> chars . at(Number( þF114F () *  þ1F0CC (chars)))) . ſ( (x,y,...𝔸)=> x + y ,   "" ) ; 

𝔓(Number) . mod  =  function(n){  return (this % n + n) % n ;  } ; 

 const  arrayLike  =  { þ0EB86  :  (x , ƒ) => { O  =  {} ; 
                         x . forEach((x) => ((y) => y in O  ? O[y] . push(x) :  (O[y] = [x]))(ƒ(x ,  ... 𝔸))) ; 
                          return O ;  } , 
               ᴍ :   (x,y,...𝔸)=> x . map(y) , 
                ꟿ  :   (x,y,...𝔸)=> x . map( (x,...𝔸)=> y( ... x)) , 
                ſ  :   (x,y,...𝔸)=> x . reduce(y) , 
                þF0232  :   (x,y,...𝔸)=> x . filter(y) , 
                þ022C0  :   (x,...𝔸)=> x . every(x ,  þF0EFE ) , 
                þ022C1  :   (x,...𝔸)=> x . some (x ,  þF0EFE ) }
𝒪(arrayLike) . forEach(([s , ƒ]) => {
  window[s]  =   (x,...𝔸)=> ƒ(isElement(x) ? 𝐴 . from(x) : x ,  ... 𝔸) ; 
  𝔓(𝐴)[s]  =  function( ... 𝔸){  return ƒ(       this  ,  ... 𝔸) ; } ; 
  𝔓(𝐸)[s]  =  function( ... 𝔸){  return ƒ(𝐴 . from(this) ,  ... 𝔸) ; } ;  }) ; 

GID  =   (x,...𝔸)=> document . getElementById(x) ; 
VAL  =   (x,...𝔸)=> GID(x) . value ; 
SAT  =   (x,y,z,...𝔸)=> x . setAttribute(y , z) ; 
QS   =  (x , ε = document) => ε . querySelector(x) ; 
QSA  =  (x , ε = document) => [ ... ε . querySelectorAll(x)] ; 
𝔏𝔖  =  { þ02191 :   (x,y,...𝔸)=> localStorage[x]  =  𝔍 . þ02191(y) , 
       þ02193 :   (x,y,...𝔸)=> x in localStorage ? 𝔍 . þ02193(localStorage[x]) : y , 
       þ02E13 :   (x,y,z,...𝔸)=> 𝔏𝔖 . þ02191(x ,  y(𝔏𝔖 . þ02193(x ,  z))) }

isStr      =   (x,...𝔸)=> typeof x  ===  "string"
isArray    =   (x,...𝔸)=> x instanceof Array
isElement  =   (x,...𝔸)=> x instanceof Element  ||  x instanceof HTMLDocument ;   


chainIntoElements  =  (x , P) => {
     if ( ! (isArray(x)  ||  isStr(x)  ||  isElement(x)))
        x  =  [] ; 
     else     if ( ! isArray(x)) x  =  [x] ; 
        x  =  x . ᴍ((𝚎) => isStr(𝚎)  ? þF0219 . createTextNode(𝚎) :  𝚎) ; 
     if (P ===  undefined )  return x
    P . append( ... x) ; 
     return P ;  }

mkə  =  (name , attrs , kids) => {
     const  remaps  =  { closedby : "closedBy" ,  NAME : "T" ,  𝑇𝐼 : "tabIndex" ,  𝑃𝐻 : "placeholder" ,  𝑇 : "type" ,  𝐼 : "id" ,  𝐶 : "className" } ; 
    kids  =  chainIntoElements(kids) ; 
     if (𝗙(name))  return name(attrs ,   ... kids)
     if (name ===  false ) name  =  "div" ; 
     let  ə  =  þF0219 . createElement(name) ; 
    ə . append( ... kids)
     if (attrs)  for ( let  [k , v]  of  𝒪(attrs)) {
       if (k == `𝑆`) ə . style . cssText  =  v ; 
       else         ə[remaps[k] ?? k]  =  v ; 
    }
    
     return ə ;  } ; 