/* AUTOGENERATED */







 const  boxy  =   (...𝔸)=> dragItem(mkə(`div` , {[`𝑆`] : `width: 25px; height: 25px; margin: 5px; background-color: #808;`} , ``) ,  `1`) ; 
þF0219 . body . append(
   print (dragHold(mkə(`div` , {[`𝑆`] : `display: flex; flex-direction: column;`} ,  þ02B65 (5) . ᴍ(boxy)) ,  `1`))
) ; 