FROM python:3.13-slim
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
WORKDIR /moon
COPY . .
RUN ./install
EXPOSE 8000
WORKDIR /moon/Libraries/WebInterface
CMD ["sh", "-c", "☾ --update && ☾ server.☾ 8000"]